from . import menyular
from . import savat
from . import buyurtmalartarixi
from . import settings
from . import help
from . import start
from . import echo
from . import contact
from . import mahsulotlar
from . import button_updater
